<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php echo $this->aboutMe['name']; ?></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
    <link rel="icon" href="img/favicon.ico" type="image/x-icon" />
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="container">

    <div class="row">
        <div class="col-xs-12">
            <div id="photo-header" class="text-center">
                <div id="photo">
                    <img src="img/avatar.jpg" alt="avatar">
                </div>
                <div id="text-header">
                    <h1>Olá,<br> meu nome é <span><?php echo $this->aboutMe['shortName']; ?></span> e isso é um pouco sobre mim</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-xs-12 col-sm-7">

            <!-- ABOUT ME -->
            <div class="box">
                <h2>About Me</h2>
                <p><?php echo $this->aboutMe['description']; ?></p>
            </div>

            <!-- EDUCATION -->
            <div class="box">
                <h2>Formação</h2>
                <ul id="education" class="clearfix">
                    <?php foreach ($this->education as $item) : ?>
                    <li>
                        <div class="year pull-left"><?php echo $item['ano'] ?></div>
                        <div class="description pull-right">
                            <h3><?php echo $item['titulo'] ?></h3>
                            <p><?php echo $item['nivel'] ?>, <?php echo $item['instituicao'] ?></p>
                        </div>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <!-- EXPERIENCES -->
            <div class="box">
                <h2>Experiências</h2>
                <?php foreach ($this->experience as $item) : ?>
                <div class="job clearfix">
                    <div class="col-xs-3">
                        <div class="where"><?php echo $item['where'] ?></div>
                        <div class="year"><?php echo $item['year'] ?></div>
                    </div>
                    <div class="col-xs-9">
                        <div class="profession"><?php echo $item['profession'] ?></div>
                        <div class="description"><?php echo $item['description'] ?></div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>

            <div class="box">
                <h2>Cursos Livres</h2>
                <?php foreach ($this->cursoLivre as $item) : ?>
                <div class="job clearfix">
                    <div class="col-xs-12">
                        <div class="profession"><?php echo $item['info1'] ?></div>
                        <div class="description"><?php echo $item['info2'] ?></div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>

        </div>

        <div class="col-xs-12 col-sm-5">

            <!-- CONTACT -->
            <div class="box clearfix">
                <h2>Contatos</h2>
                <?php foreach ($this->contact as $item) : ?>
                <div class="contact-item">
                    <div class="icon pull-left text-center">
                        <span class="fa fa-<?php echo $item['icon'] ?> fa-fw"></span>
                    </div>
                    <?php if (isset($item['title'])) : ?>
                        <div class="title <?php if (!isset($item['description'])) : ?>only<?php endif; ?> pull-right">
                            <?php echo $item['title'] ?>
                        </div>
                    <?php endif; ?>
                    <?php if (isset($item['description'])) : ?>
                        <div class="description <?php if (!isset($item['title'])) : ?>only<?php endif; ?> pull-right">
                            <?php echo $item['description'] ?>
                        </div>
                    <?php endif; ?>
                </div>
                <?php endforeach; ?>
            </div>

            <!-- SKILLS -->
            <div class="box">
                <h2>Skills</h2>
                <div class="skills">
                    <?php foreach ($this->skill as $item) : ?>
                    <div class="item-skills" data-percent="<?php echo $item['percent']; ?>">
                        <?php echo $item['description']; ?>
                    </div>
                    <?php endforeach; ?>
                    <div class="skills-legend clearfix">
                        <div class="legend-left legend">Beginner</div>
                        <div class="legend-left legend"><span>Proficient</span></div>
                        <div class="legend-right legend"><span>Expert</span></div>
                        <div class="legend-right legend">Master</div>
                    </div>
                </div>
            </div>

            <!-- LANGUAGES -->
            <div class="box">
                <h2>Idiomas</h2>
                <div id="language-skills">
                    <?php foreach ($this->language as $item) : ?>
                    <div class="skill"><?php echo $item['description'] ?>
                        <div class="icons pull-right">
                            <div style="width: <?php echo $item['percent'] ?>%;" class="icons-red"></div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <!-- HOBBIES -->
            <div class="box">
                <h2>Hobbies</h2>
                <?php foreach ($this->hobby as $item) : ?>
                <div class="hobby"><?php echo $item['description'] ?></div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>


<!-- JQUERY -->
<script src="js/jquery.min.js"></script>
<!-- BOOTSTRAP -->
<script src="js/bootstrap.min.js"></script>
<!-- SCRIPTS -->
<script src="js/scripts.js"></script>

</body>
</html>
